### ISSUE TITLE
How to remove default horizontal padding?

### ISSUE THREAD

**Issue by TangSirOnGit** [Daniel-Ioannou/flutter_group_list_view#17]
How to remove default horizontal padding?

I config the padding as:

```
child: GroupListView(
          // padding: EdgeInsets.zero,
          padding: const EdgeInsets.symmetric(horizontal: 0, vertical: 4),
```
 but it doesn't work.

<img width="435" alt="image" src="https://user-images.githubusercontent.com/10524715/191652338-ac1d7333-757c-42f2-a8b4-ced525ee917c.png">

**Comment by Daniel-Ioannou** [comment]
@TangSirOnGit Package dose not defined a default horizontal padding. Maybe you have defined a horizontal padding in `itemBuilder` or the father widget of the GroupListView has a padding.

In the package padding [example](https://pub.dev/packages/group_list_view/example) code padding is defined in each row at `itemBuilder`.

Or the following code does not have horizontal padding:
 ```Dart
  Map<String, List> _elements = {
    'Team A': ['Klay Lewis', 'Ehsan Woodard', 'River Bains'],
    'Team B': ['Toyah Downs', 'Tyla Kane'],
  };

GroupListView(
    sectionsCount: _elements.keys.toList().length,
    countOfItemInSection: (int section) {
        return _elements.values.toList()[section].length;
    },
    itemBuilder: (BuildContext context, IndexPath index) {
        return Text(
            _elements.values.toList()[index.section][index.index],
            style: TextStyle(fontSize: 16, fontWeight: FontWeight.w400),
        );
    },
    groupHeaderBuilder: (BuildContext context, int section) {
        return Text(
            _elements.keys.toList()[section],
            style: TextStyle(fontSize: 18, fontWeight: FontWeight.w600),
        );
    },
    separatorBuilder: (context, index) => SizedBox(height: 10),
    sectionSeparatorBuilder: (context, section) => SizedBox(height: 10),
);

```

<img src="https://user-images.githubusercontent.com/15341488/192141752-e6bfb55f-98a8-4acc-bb66-ddbbce81d3b8.png" width="250"  />

**Comment by TangSirOnGit** [comment]
@Daniel-Ioannou  Thank you for your reply.
