### ISSUE TITLE
Support sectionSeparatorBuilder

### ISSUE THREAD

**Issue by omidraha** [Daniel-Ioannou/flutter_group_list_view#4]
Hi,
Currently `separatorBuilder` is  used for separating items,
It's nice if we have  also `sectionSeparatorBuilder`  to separate between sections. 

Currently:

```
H1
Item1
----
Item2
----
H2
Item1
----
Item2
----
```
I wish:
```
H1
Item1
----
Item2
====
H2
Item1
----
Item2
===
```

**Comment by omidraha** [comment]
Solution without that:
```dart
  separatorBuilder: (context, index) {
	if (index.index + 1 == _elements.values.toList()[index.section].length) {
	  return Divider();
	} else {
	  return Divider(indent: 20, endIndent: 20);
	}
  },
```

**Comment by omidraha** [comment]
Thanks !

**Comment by Daniel-Ioannou** [comment]
@omidraha `sectionSeparatorBuilder` was added at version 1.0.6. For more details please check the documentation [HERE](https://pub.dev/documentation/group_list_view/latest/group_list_view/GroupListView/sectionSeparatorBuilder.html).
